# Generated by Django 4.1.5 on 2023-02-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=5000, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
